nav:
    - Introduction: index.md
    - Event-driven-model: Event-driven-model
    - Application-protocol: Application-protocol
    - Stream-based-message-processing-system: Stream-based-message-processing-system
    - Message-queue: Message-queue